declare const _default: {
    LINEAR: string;
    BEZIER: string;
    HOLD: string;
    none: number[];
    inQuad: number[];
    inCubic: number[];
    inQuart: number[];
    inQuint: number[];
    inSine: number[];
    inExpo: number[];
    inCirc: number[];
    inBack: number[];
    outQuad: number[];
    outCubic: number[];
    outQuart: number[];
    outQuint: number[];
    outSine: number[];
    outExpo: number[];
    outCirc: number[];
    outBack: number[];
    inOutQuad: number[];
    inOutCubic: number[];
    inOutQuart: number[];
    inOutQuint: number[];
    inOutSine: number[];
    inOutExpo: number[];
    inOutCirc: number[];
    inOutBack: number[];
};
export default _default;
//# sourceMappingURL=Ease.d.ts.map